# Project information
site_name: Kaguya-samaWannaMeAC-Wiki
site_url: https://kaguya-samawannameac.github.io/
site_author: Kaguya-samaWannaMeAC

# Repository
repo_name: Kaguya-samaWannaMeAC
repo_url: https://github.com/kaguya-samawannameac/kaguya-samawannameac.github.io
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 - 2021 Kaguya-samaWannaMeAC

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kaguya-samawannameac
    - icon: fontawesome/brands/qq
      link: https://codeforces.com

theme:
  name: material
  palette:
    primary: 'White'
    accent: 'Pink'
  features:
    - navigation.tabs
    - toc.integrate
  language: 'zh'
  favicon: 'https://cdn.jsdelivr.net/npm/oicdn@0.0.1/favicon.ico'
  icon:
    logo: material/school
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - 'js/extra.js'
  - 'https://polyfill.io/v3/polyfill.min.js?features=es6'
  - 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'

nav:
  - 首页: index.md
  - 比赛记录: 
    - WA on test 998244353: contest/WA on test 998244353.md
    - 比赛模板: contest/template.md
    - 2020-05-10~2020-12-13:
        - 2020-05-10 SEERC 2016 D: contest/2020-05-10 SEERC2016.md
        - 2020-05-17 2017-2018 NEERC Moscow D: contest/2020-05-17 2017-2018 NEERC Moscow.md
        - 2020-05-24 2009-2010 NEERC Western D: contest/2020-05-24 2009-2010 NEERC Western.md
        - 2020-07-12 2020牛客暑期多校第一场 D: contest/2020-07-12 2020牛客暑期多校第一场.md
        - 2020-07-13 2020牛客暑期多校第二场 D: contest/2020-07-13 2020牛客暑期多校第二场.md
        - 2020-07-18 2020牛客暑期多校第三场 D: contest/2020-07-18 2020牛客暑期多校第三场.md
        - 2020-07-20 2020牛客暑期多校第四场 D: contest/2020-07-20 2020牛客暑期多校第四场.md
        - 2020-07-22 2020HDU暑期多校第一场 U: contest/2020-07-22 2020HDU暑期多校第一场.md
        - 2020-07-23 2020-2021 BUAA Training 01 D: contest/2020-07-23 2020-2021 BUAA ICPC Team Supplementary Training 01.md
        - 2020-07-25 2020牛客暑期多校第五场 D: contest/2020-07-25 2020牛客暑期多校第五场.md
        - 2020-07-20 2020牛客暑期多校第六场 U: contest/2020-07-27 2020牛客暑期多校第六场.md
        - 2020-07-29 2020HDU暑期多校第二场 U: contest/2020-07-29 2020HDU暑期多校第二场.md
        - 2020-08-01 2020牛客暑期多校第七场 U: contest/2020-08-01 2020牛客暑期多校第七场.md
        - 2020-08-03 2020牛客暑期多校第八场 U: contest/2020-08-03 2020牛客暑期多校第八场.md
        - 2020-08-06 2020-2021 BUAA Training 02 U: contest/2020-08-06 2020-2021 BUAA ICPC Team Supplementary Training 02.md
        - 2020-08-08 2020牛客暑期多校第九场 U: contest/2020-08-08 2020牛客暑期多校第九场.md
        - 2020-08-10 2020牛客暑期多校第十场 U: contest/2020-08-10 2020牛客暑期多校第十场.md
        - 2020-08-13 2020HDU暑期多校第六场 U: contest/2020-08-13 2020HDU暑期多校第六场.md
        - 2020-08-20 2020HDU暑期多校第七场 U: contest/2020-08-20 2020HDU暑期多校第七场.md
        - 2020-09-13 2016 CCPC 长春站 U: contest/2020-09-13 2016 CCPC 长春站.md
        - 2020-09-19 2020-2021 BUAA Training 03 U: contest/2020-09-19 2020-2021 BUAA ICPC Team Supplementary Training 03.md
        - 2020-09-20 2020 CCPC 网络赛 U: contest/2020-09-20 2020 CCPC 网络赛.md
        - 2020-09-26 2020-2021 BUAA Training 04 U: contest/2020-09-26 2020-2021 BUAA ICPC Team Supplementary Training 04.md
        - 2020-09-27 2020-2021 BUAA Training 05 U: contest/2020-09-27 2020-2021 BUAA ICPC Team Supplementary Training 05.md
        - 2020-10-04 2016-2017 NEERC Southern U: contest/2020-10-04 2016-2017 ACM-ICPC, NEERC, Southern Subregional Contest.md
        - 2020-10-07 2016 CCPC 合肥站 U: contest/2020-10-07 2016 CCPC 合肥站.md
        - 2020-10-10 2016 ICPC 沈阳站 U: contest/2020-10-10 2016 ICPC 沈阳站.md
        - 2020-11-18 2015 ICPC 上海站 U: contest/2020-11-18 2015 ICPC 上海站.md
        - 2020-11-21 2015-2016 NEERC Moscow U: contest/2020-11-21 2015-2016 ACM-ICPC, NEERC, Moscow Subregional Contest.md
        - 2020-12-05 2020 CCPC 长春站 U: contest/2020-12-05 2020 CCPC 长春站.md
        - 2020-12-09 2020 CCPC 绵阳站 U: contest/2020-12-09 2020 CCPC 绵阳站.md
        - 2020-12-13 2020 ICPC 上海站 U: contest/2020-12-13 2020 ICPC 上海站.md
    - 2020-12-14~:          
        - 2020-12-16 XIX Open Cup SPb Div1 U: contest/2020-12-16 XIX Open Cup SPb Div1.md
        - 2020-12-23 XIX Open Cup Korea Div1 D: contest/2020-12-23 XIX Open Cup Korea Div1.md
        - 2020-12-30 2020 ICPC 南京 U: contest/2020-12-30 2020 ICPC 南京.md
        - 2021-01-15 2020 ICPC 济南 U: contest/2021-01-15 2020 ICPC 济南.md
        - 2021-01-20 MIPTCamp 2016 National Taiwan U: contest/2021-01-20 MIPTCamp 2016 National Taiwan U Contest.md
        - 2021-01-26 Namomo Winter Camp 1: contest/2021-01-26 Namomo Winter Camp 1.md
        - 2021-01-27 Namomo Winter Camp 2: contest/2021-01-27 Namomo Winter Camp 2.md
        - 2021-01-29 Namomo Winter Camp 3: contest/2021-01-29 Namomo Winter Camp 3.md
        - 2021-01-30 Namomo Winter Camp 4: contest/2021-01-30 Namomo Winter Camp 4.md
        - 2021-01-31 Namomo Camp 2021 Contest: contest/2021-01-31 Namomo Camp 2021 Contest.md
        - 2021-02-19 XIX Open Cup Moscow Workshops: contest/2021-02-19 XIX Open Cup Moscow Workshops.md
        - 2021-02-24 Petrozavodsk Winter 2018 ITMO U 1 Contest: contest/2021-02-24 Petrozavodsk Winter 2018 ITMO U 1 Contest.md
        - 2021-03-06 Petrozavodsk Winter 2019 The Japanese Contest: contest/2021-03-06 Petrozavodsk Winter 2019 The Japanese Contest.md
        - 2021-03-17 Petrozavodsk Winter-2018. Jagiellonian U Contest: contest/2021-03-17 Petrozavodsk Winter-2018. Jagiellonian U Contest.md
        - 2021-03-27 2015 EC Final: contest/2021-03-27 2015 EC Final.md
        - 2021-04-07 2019-2020 ICPC Asia Hong Kong Regional Contest: contest/2021-04-07 2019-2020 ICPC Asia Hong Kong Regional Contest.md
        - 2021-04-11 2020 ICPC 昆明: contest/2021-04-12 2020 ICPC 昆明.md
  - 知识点: 
    - TLE on test 1000000007: 知识点/TLE on test 1000000007.md
    - 拟阵: 知识点/拟阵.md
    - 计数问题: 知识点/计数问题.md
  - 2sozx: 
    - 个人首页: 2sozx/index.md
    - 2021-01-01~: 2sozx/2021-01-01~.md
    - IOI2020 集训队作业: 2sozx/IOI2020集训.md
  - Bazoka13: 
    - 个人首页: Bazoka13/index.md
    - BUG整理: Bazoka13/BazokaBug.md
    - 拟阵交: Bazoka13/MatroidIntersection.md
    - 弦图: Bazoka13/ChordalGraph.md
    - 2021-02: Bazoka13/202102.md
  - JJLeo: 
    - 个人首页: JJLeo/index.md
    - 2020-12-13~2021-01-13: JJLeo/2020-12-13~2021-01-13.md
    - 2021-01-14~2021-02-28: JJLeo/2021-01-14~2021-02-28.md
    - 套路总结: JJLeo/套路总结.md
    - 2020 CCPC Wannafly Winter Camp Day1: JJLeo/2020 CCPC Wannafly Winter Camp Day1.md
    - 2020 CCPC Wannafly Winter Camp Day2: JJLeo/2020 CCPC Wannafly Winter Camp Day2.md
    - 2020 CCPC Wannafly Winter Camp Day3: JJLeo/2020 CCPC Wannafly Winter Camp Day3.md
    - 2020 CCPC Wannafly Winter Camp Day5: JJLeo/2020 CCPC Wannafly Winter Camp Day5.md
    - 2020 CCPC Wannafly Winter Camp Day6: JJLeo/2020 CCPC Wannafly Winter Camp Day6.md
    - 2021-03-01~: JJLeo/2021-03-01~.md
    - IOI2020 集训队作业: JJLeo/IOI2020 集训队作业.md
  - 杂项:
    - E2-hard-solution: 杂项/E2-hard-solution.md
  
